/**
 * CodeMirror 6 extension for Suggest mode.
 *
 * When active, intercepts CM6 transactions and transforms user edits into
 * CriticMark annotations instead of modifying text directly:
 *
 *   - Typing new text  -> {++@username: new text++}
 *   - Deleting text     -> {--@username: deleted text--}
 *   - Replacing text    -> {~~@username: old~>new~~}
 *
 * The mode is controlled via a StateField that stores the current mode and
 * username. A transaction filter checks this field and rewrites transactions
 * accordingly.
 */

import {
  StateField,
  StateEffect,
  Annotation,
  EditorState,
  Transaction,
  type TransactionSpec,
} from "@codemirror/state";
import { ySyncFacet } from "y-codemirror.next";
import type { EditorMode } from "./modes";

// ---------------------------------------------------------------------------
// State: current mode + username
// ---------------------------------------------------------------------------

export interface SuggestModeState {
  mode: EditorMode;
  username: string;
}

/** Effect to update the suggest-mode state (mode and/or username). */
export const setSuggestModeEffect = StateEffect.define<Partial<SuggestModeState>>();

/** StateField tracking the current editor mode and username. */
export const suggestModeField = StateField.define<SuggestModeState>({
  create() {
    return { mode: "edit", username: "" };
  },
  update(value, tr) {
    for (const effect of tr.effects) {
      if (effect.is(setSuggestModeEffect)) {
        return { ...value, ...effect.value };
      }
    }
    return value;
  },
});

// ---------------------------------------------------------------------------
// Annotation to mark our own CriticMark-generated transactions
// ---------------------------------------------------------------------------

/**
 * We annotate transactions generated by the suggest-mode filter so we
 * don't re-filter them in a recursive dispatch.
 */
const suggestModeAnnotation = Annotation.define<boolean>();

// ---------------------------------------------------------------------------
// Transaction filter: rewrite edits as CriticMark in suggest mode
// ---------------------------------------------------------------------------

/**
 * Detect whether a transaction is a remote Yjs sync. y-codemirror.next
 * annotates remote dispatches with ySyncAnnotation.of(config) where config
 * is the ySyncFacet value. Since ySyncAnnotation isn't in the public exports,
 * we detect remote transactions by checking if ANY annotation on the
 * transaction has a value that matches the ySyncFacet config object.
 */
function isRemoteYjsTransaction(tr: Transaction): boolean {
  // Get the ySyncFacet config from the state. If there's no yCollab
  // extension, the facet returns undefined.
  const syncConfig = tr.startState.facet(ySyncFacet);
  if (!syncConfig) return false;

  // Check all annotations - the ySync plugin annotates with the config object.
  // We iterate through transaction annotations by checking if we can read
  // the value. Unfortunately CM6 doesn't expose a way to iterate all
  // annotations. Instead, we use a heuristic: if the transaction has doc
  // changes but no user event annotation, it's likely remote.
  // The ySync plugin doesn't set Transaction.userEvent.
  const userEvent = tr.annotation(Transaction.userEvent);
  if (userEvent !== undefined) return false;

  // If there's no user event and there are changes, check if the changes
  // could be from our own filter (which we mark with suggestModeAnnotation).
  if (tr.annotation(suggestModeAnnotation)) return false;

  // Heuristic: transactions from CM6 input handling always have a userEvent.
  // Yjs remote transactions don't. If there's no userEvent and no
  // suggestModeAnnotation, this is likely a remote or programmatic change.
  // We should NOT intercept those.
  return true;
}

/**
 * A CM6 transactionFilter that, when suggest mode is active, rewrites
 * insert/delete/replace operations into CriticMark annotation insertions.
 *
 * Passes through:
 *   - transactions with no document changes (selection, scroll, etc.)
 *   - remote Yjs sync transactions
 *   - transactions already generated by this filter
 */
function suggestModeFilter(tr: Transaction): TransactionSpec | readonly TransactionSpec[] {
  // Pass through if no doc changes
  if (!tr.docChanged) return tr;

  const state = tr.startState;
  const smState = state.field(suggestModeField, false);

  // Not in suggest mode? Pass through.
  if (!smState || smState.mode !== "suggest") return tr;

  // Don't re-filter our own generated transactions.
  if (tr.annotation(suggestModeAnnotation)) return tr;

  // Don't intercept remote Yjs sync transactions.
  if (isRemoteYjsTransaction(tr)) return tr;

  const username = smState.username;
  const doc = state.doc;

  // Collect all the changes.
  const changes: { from: number; to: number; inserted: string }[] = [];

  tr.changes.iterChanges((fromA, toA, _fromB, _toB, inserted) => {
    changes.push({ from: fromA, to: toA, inserted: inserted.toString() });
  });

  if (changes.length === 0) return tr;

  // Build CriticMark replacements, sorted by position (ascending).
  const replacements: { from: number; to: number; insert: string }[] = [];

  for (const change of changes) {
    const { from, to, inserted } = change;
    const deletedText = doc.sliceString(from, to);
    const hasInsert = inserted.length > 0;
    const hasDelete = deletedText.length > 0;

    let criticMarkText: string;

    if (hasInsert && hasDelete) {
      // Replacement -> substitution
      criticMarkText = `{~~@${username}: ${deletedText}~>${inserted}~~}`;
    } else if (hasDelete) {
      // Pure deletion
      criticMarkText = `{--@${username}: ${deletedText}--}`;
    } else if (hasInsert) {
      // Pure insertion
      criticMarkText = `{++@${username}: ${inserted}++}`;
    } else {
      continue;
    }

    replacements.push({ from, to, insert: criticMarkText });
  }

  if (replacements.length === 0) return tr;

  // Sort ascending by `from` for the changeset builder.
  replacements.sort((a, b) => a.from - b.from);

  // Compute cursor position: end of last replacement in the new document.
  // We need to account for how earlier replacements shift later positions.
  let shift = 0;
  let cursorPos = 0;
  for (const r of replacements) {
    const newFrom = r.from + shift;
    const newEnd = newFrom + r.insert.length;
    cursorPos = newEnd;
    shift += r.insert.length - (r.to - r.from);
  }

  return {
    changes: replacements,
    selection: { anchor: cursorPos },
    annotations: suggestModeAnnotation.of(true),
  };
}

// ---------------------------------------------------------------------------
// Public extension: combines the state field + transaction filter
// ---------------------------------------------------------------------------

/**
 * Returns the suggest mode extension (state field + transaction filter).
 * Add this to your editor's extensions array.
 */
export function suggestMode() {
  return [suggestModeField, EditorState.transactionFilter.of(suggestModeFilter)];
}
